services:
    vemu:
        image: docker-emulator
        container_name: emulator
        ports:
            - 6080:6080
        working_dir: /usr/src/app
        volumes:
            - ./app:/usr/src/app
        devices:
            - /dev/kvm
        environment:
            - VNC_PASSWORD=no
        privileged: true