[supervisord]
nodaemon=true

[program:tigervncserver]
environment=HOME="/root",DISPLAY=":0",USER="root"
command=tigervncserver -localhost no -fg :0
autorestart=true
priority=1

[program:emulator]
environment=HOME="/root",DISPLAY=":0",USER="root",PWD="/root"
command=/etc/launch_emulator.sh
stdout_logfile=/tmp/device.stdout.log
redirect_stderr=true
autorestart=true
priority=500

[program:tint2]
environment=DISPLAY=":0"
command=tint2 -c /etc/xdg/tint2/tint2rc
autorestart=true
priority=2000

[program:novnc_proxy]
command=/opt/noVNC/utils/novnc_proxy --vnc localhost:5900 localhost:6080
autostart=true
autorestart=true
stdout_logfile=/tmp/vnc_server.stdout.log
stderr_logfile=/tmp/vnc_server.stderr.log
redirect_stderr=false
priority=4000

[program:appium]
environment=HOME="/root",DISPLAY=":0",USER="root"
command=/usr/bin/xfce4-terminal -x "/etc/launch_appium.sh"
autorestart=true
priority=5000

[program:metro]
environment=HOME="/root",DISPLAY=":0",USER="root",PWD="/root"
directory = /usr/src/app
startsecs = 35
command=bash -c 'sleep 30 && /usr/bin/xfce4-terminal -x npm run start'
autostart=true
process_name=metro
priority=6000

[program:reactnative]
environment=HOME="/root",DISPLAY=":0",USER="root",PWD="/root"
directory = /usr/src/app
startsecs = 45
command=bash -c 'sleep 40 && /usr/bin/xfce4-terminal -x npx react-native run-android'
autostart=true
autorestart=false
process_name=reactnative
priority=7000
