FROM docker-emulator:ubuntu

EXPOSE 5900 

ENV HOME=/root
ENV TZ=Etc/UTC
ENV SHELL=/bin/bash
ENV PS1='# '
ENV DEBIAN_FRONTEND=noninteractive
ENV PASSWORD="root"

RUN apt install -y \
  supervisor \
  openbox tint2 \
  pcmanfm xfce4-terminal procps curl telnet iproute2 

# NOTE: vnc setup start
RUN apt install -qy tigervnc-standalone-server
RUN mkdir /root/.vnc
RUN echo 123456 | vncpasswd -f > /root/.vnc/passwd
RUN chmod 600 /root/.vnc/passwd
# NOTE: vnc setup done

ADD etc/xdg/pcmanfm /root/.config/pcmanfm
ADD etc /etc

# NOTE: Customize Onyx theme to make the menu white
RUN mkdir -p /usr/share/themes/Onyx/openbox-3 && \
    touch /usr/share/themes/Onyx/openbox-3/themerc && \
    echo 'menu.border.color: #ffffff\n\
menu.title.bg: flat\n\
menu.title.bg.color: #ffffff\n\
menu.title.text.color: #000000\n\
menu.items.bg: flat\n\
menu.items.bg.color: #ffffff\n\
menu.items.text.color: #000000\n\
menu.items.active.bg: flat\n\
menu.items.active.bg.color: #0096ff\n\
menu.items.active.text.color: #ffffff\n\
menu.separator.color: #e0e0e0' >> /usr/share/themes/Onyx/openbox-3/themerc

# # original openbox docker ends here

# launch line
# CMD ["/usr/bin/supervisord","-c","/etc/supervisord-screen.conf"]
